export const countries = [
  { name: 'Afghanistan', a2: 'AF', a3: 'AFG', num: '004' },
  { name: 'Åland Islands', a2: 'AX', a3: 'ALA', num: '248' },
  { name: 'Albania', a2: 'AL', a3: 'ALB', num: '008' },
  { name: 'Algeria', a2: 'DZ', a3: 'DZA', num: '012' },
  { name: 'American Samoa', a2: 'AS', a3: 'ASM', num: '016' },
  { name: 'Andorra', a2: 'AD', a3: 'AND', num: '020' },
  { name: 'Angola', a2: 'AO', a3: 'AGO', num: '024' },
  { name: 'Anguilla', a2: 'AI', a3: 'AIA', num: '660' },
  { name: 'Antarctica', a2: 'AQ', a3: 'ATA', num: '010' },
  { name: 'Antigua and Barbuda', a2: 'AG', a3: 'ATG', num: '028' },
  { name: 'Argentina', a2: 'AR', a3: 'ARG', num: '032' },
  { name: 'Armenia', a2: 'AM', a3: 'ARM', num: '051' },
  { name: 'Aruba', a2: 'AW', a3: 'ABW', num: '533' },
  { name: 'Australia', a2: 'AU', a3: 'AUS', num: '036' },
  { name: 'Austria', a2: 'AT', a3: 'AUT', num: '040' },
  { name: 'Azerbaijan', a2: 'AZ', a3: 'AZE', num: '031' },
  { name: 'Bahamas', prefix: 'the', a2: 'BS', a3: 'BHS', num: '044' },
  { name: 'Bahrain', a2: 'BH', a3: 'BHR', num: '048' },
  { name: 'Bangladesh', a2: 'BD', a3: 'BGD', num: '050' },
  { name: 'Barbados', a2: 'BB', a3: 'BRB', num: '052' },
  { name: 'Belarus', a2: 'BY', a3: 'BLR', num: '112' },
  { name: 'Belgium', a2: 'BE', a3: 'BEL', num: '056' },
  { name: 'Belize', a2: 'BZ', a3: 'BLZ', num: '084' },
  { name: 'Benin', a2: 'BJ', a3: 'BEN', num: '204' },
  { name: 'Bermuda', a2: 'BM', a3: 'BMU', num: '060' },
  { name: 'Bhutan', a2: 'BT', a3: 'BTN', num: '064' },
  { name: 'Bolivia', prefix: 'Plurinational State of', a2: 'BO', a3: 'BOL', num: '068' },
  { name: 'Bonaire, Sint Eustatius and Saba', a2: 'BQ', a3: 'BES', num: '535' },
  { name: 'Bosnia and Herzegovina', a2: 'BA', a3: 'BIH', num: '070' },
  { name: 'Botswana', a2: 'BW', a3: 'BWA', num: '072' },
  { name: 'Bouvet Island', a2: 'BV', a3: 'BVT', num: '074' },
  { name: 'Brazil', a2: 'BR', a3: 'BRA', num: '076' },
  { name: 'British Indian Ocean Territory', prefix: 'the', a2: 'IO', a3: 'IOT', num: '086' },
  { name: 'Brunei Darussalam', a2: 'BN', a3: 'BRN', num: '096' },
  { name: 'Bulgaria', a2: 'BG', a3: 'BGR', num: '100' },
  { name: 'Burkina Faso', a2: 'BF', a3: 'BFA', num: '854' },
  { name: 'Burundi', a2: 'BI', a3: 'BDI', num: '108' },
  { name: 'Cabo Verde', a2: 'CV', a3: 'CPV', num: '132' },
  { name: 'Cambodia', a2: 'KH', a3: 'KHM', num: '116' },
  { name: 'Cameroon', a2: 'CM', a3: 'CMR', num: '120' },
  { name: 'Canada', a2: 'CA', a3: 'CAN', num: '124' },
  { name: 'Cayman Islands', prefix: 'the', a2: 'KY', a3: 'CYM', num: '136' },
  { name: 'Central African Republic', prefix: 'the', a2: 'CF', a3: 'CAF', num: '140' },
  { name: 'Chad', a2: 'TD', a3: 'TCD', num: '148' },
  { name: 'Chile', a2: 'CL', a3: 'CHL', num: '152' },
  { name: 'China', a2: 'CN', a3: 'CHN', num: '156' },
  { name: 'Christmas Island', a2: 'CX', a3: 'CXR', num: '162' },
  { name: 'Cocos (Keeling) Islands', prefix: 'the', a2: 'CC', a3: 'CCK', num: '166' },
  { name: 'Colombia', a2: 'CO', a3: 'COL', num: '170' },
  { name: 'Comoros', prefix: 'the', a2: 'KM', a3: 'COM', num: '174' },
  { name: 'Congo', prefix: 'the Democratic Republic of the', a2: 'CD', a3: 'COD', num: '180' },
  { name: 'Congo', prefix: 'the', a2: 'CG', a3: 'COG', num: '178' },
  { name: 'Cook Islands', prefix: 'the', a2: 'CK', a3: 'COK', num: '184' },
  { name: 'Costa Rica', a2: 'CR', a3: 'CRI', num: '188' },
  { name: "Côte d'Ivoire", a2: 'CI', a3: 'CIV', num: '384' },
  { name: 'Croatia', a2: 'HR', a3: 'HRV', num: '191' },
  { name: 'Cuba', a2: 'CU', a3: 'CUB', num: '192' },
  { name: 'Curaçao', a2: 'CW', a3: 'CUW', num: '531' },
  { name: 'Cyprus', a2: 'CY', a3: 'CYP', num: '196' },
  { name: 'Czechia', a2: 'CZ', a3: 'CZE', num: '203' },
  { name: 'Denmark', a2: 'DK', a3: 'DNK', num: '208' },
  { name: 'Djibouti', a2: 'DJ', a3: 'DJI', num: '262' },
  { name: 'Dominica', a2: 'DM', a3: 'DMA', num: '212' },
  { name: 'Dominican Republic', prefix: 'the', a2: 'DO', a3: 'DOM', num: '214' },
  { name: 'Ecuador', a2: 'EC', a3: 'ECU', num: '218' },
  { name: 'Egypt', a2: 'EG', a3: 'EGY', num: '818' },
  { name: 'El Salvador', a2: 'SV', a3: 'SLV', num: '222' },
  { name: 'Equatorial Guinea', a2: 'GQ', a3: 'GNQ', num: '226' },
  { name: 'Eritrea', a2: 'ER', a3: 'ERI', num: '232' },
  { name: 'Estonia', a2: 'EE', a3: 'EST', num: '233' },
  { name: 'Eswatini', a2: 'SZ', a3: 'SWZ', num: '748' },
  { name: 'Ethiopia', a2: 'ET', a3: 'ETH', num: '231' },
  { name: 'Falkland Islands (the) [Malvinas]', a2: 'FK', a3: 'FLK', num: '238' },
  { name: 'Faroe Islands', prefix: 'the', a2: 'FO', a3: 'FRO', num: '234' },
  { name: 'Fiji', a2: 'FJ', a3: 'FJI', num: '242' },
  { name: 'Finland', a2: 'FI', a3: 'FIN', num: '246' },
  { name: 'France', a2: 'FR', a3: 'FRA', num: '250' },
  { name: 'French Guiana', a2: 'GF', a3: 'GUF', num: '254' },
  { name: 'French Polynesia', a2: 'PF', a3: 'PYF', num: '258' },
  { name: 'French Southern Territories', prefix: 'the', a2: 'TF', a3: 'ATF', num: '260' },
  { name: 'Gabon', a2: 'GA', a3: 'GAB', num: '266' },
  { name: 'Gambia', prefix: 'the', a2: 'GM', a3: 'GMB', num: '270' },
  { name: 'Georgia', a2: 'GE', a3: 'GEO', num: '268' },
  { name: 'Germany', a2: 'DE', a3: 'DEU', num: '276' },
  { name: 'Ghana', a2: 'GH', a3: 'GHA', num: '288' },
  { name: 'Gibraltar', a2: 'GI', a3: 'GIB', num: '292' },
  { name: 'Greece', a2: 'GR', a3: 'GRC', num: '300' },
  { name: 'Greenland', a2: 'GL', a3: 'GRL', num: '304' },
  { name: 'Grenada', a2: 'GD', a3: 'GRD', num: '308' },
  { name: 'Guadeloupe', a2: 'GP', a3: 'GLP', num: '312' },
  { name: 'Guam', a2: 'GU', a3: 'GUM', num: '316' },
  { name: 'Guatemala', a2: 'GT', a3: 'GTM', num: '320' },
  { name: 'Guernsey', a2: 'GG', a3: 'GGY', num: '831' },
  { name: 'Guinea', a2: 'GN', a3: 'GIN', num: '324' },
  { name: 'Guinea-Bissau', a2: 'GW', a3: 'GNB', num: '624' },
  { name: 'Guyana', a2: 'GY', a3: 'GUY', num: '328' },
  { name: 'Haiti', a2: 'HT', a3: 'HTI', num: '332' },
  { name: 'Heard Island and McDonald Islands', a2: 'HM', a3: 'HMD', num: '334' },
  { name: 'Holy See', prefix: 'the', a2: 'VA', a3: 'VAT', num: '336' },
  { name: 'Honduras', a2: 'HN', a3: 'HND', num: '340' },
  { name: 'Hong Kong', a2: 'HK', a3: 'HKG', num: '344' },
  { name: 'Hungary', a2: 'HU', a3: 'HUN', num: '348' },
  { name: 'Iceland', a2: 'IS', a3: 'ISL', num: '352' },
  { name: 'India', a2: 'IN', a3: 'IND', num: '356' },
  { name: 'Indonesia', a2: 'ID', a3: 'IDN', num: '360' },
  { name: 'Iran', prefix: 'Islamic Republic of', a2: 'IR', a3: 'IRN', num: '364' },
  { name: 'Iraq', a2: 'IQ', a3: 'IRQ', num: '368' },
  { name: 'Ireland', a2: 'IE', a3: 'IRL', num: '372' },
  { name: 'Isle of Man', a2: 'IM', a3: 'IMN', num: '833' },
  { name: 'Israel', a2: 'IL', a3: 'ISR', num: '376' },
  { name: 'Italy', a2: 'IT', a3: 'ITA', num: '380' },
  { name: 'Jamaica', a2: 'JM', a3: 'JAM', num: '388' },
  { name: 'Japan', a2: 'JP', a3: 'JPN', num: '392' },
  { name: 'Jersey', a2: 'JE', a3: 'JEY', num: '832' },
  { name: 'Jordan', a2: 'JO', a3: 'JOR', num: '400' },
  { name: 'Kazakhstan', a2: 'KZ', a3: 'KAZ', num: '398' },
  { name: 'Kenya', a2: 'KE', a3: 'KEN', num: '404' },
  { name: 'Kiribati', a2: 'KI', a3: 'KIR', num: '296' },
  { name: 'Korea', prefix: "the Democratic People's Republic of", a2: 'KP', a3: 'PRK', num: '408' },
  { name: 'Korea', prefix: 'the Republic of', a2: 'KR', a3: 'KOR', num: '410' },
  { name: 'Kuwait', a2: 'KW', a3: 'KWT', num: '414' },
  { name: 'Kyrgyzstan', a2: 'KG', a3: 'KGZ', num: '417' },
  { name: "Lao People's Democratic Republic", prefix: 'the', a2: 'LA', a3: 'LAO', num: '418' },
  { name: 'Latvia', a2: 'LV', a3: 'LVA', num: '428' },
  { name: 'Lebanon', a2: 'LB', a3: 'LBN', num: '422' },
  { name: 'Lesotho', a2: 'LS', a3: 'LSO', num: '426' },
  { name: 'Liberia', a2: 'LR', a3: 'LBR', num: '430' },
  { name: 'Libya', a2: 'LY', a3: 'LBY', num: '434' },
  { name: 'Liechtenstein', a2: 'LI', a3: 'LIE', num: '438' },
  { name: 'Lithuania', a2: 'LT', a3: 'LTU', num: '440' },
  { name: 'Luxembourg', a2: 'LU', a3: 'LUX', num: '442' },
  { name: 'Macao', a2: 'MO', a3: 'MAC', num: '446' },
  { name: 'Republic of North Macedonia', a2: 'MK', a3: 'MKD', num: '807' },
  { name: 'Madagascar', a2: 'MG', a3: 'MDG', num: '450' },
  { name: 'Malawi', a2: 'MW', a3: 'MWI', num: '454' },
  { name: 'Malaysia', a2: 'MY', a3: 'MYS', num: '458' },
  { name: 'Maldives', a2: 'MV', a3: 'MDV', num: '462' },
  { name: 'Mali', a2: 'ML', a3: 'MLI', num: '466' },
  { name: 'Malta', a2: 'MT', a3: 'MLT', num: '470' },
  { name: 'Marshall Islands', prefix: 'the', a2: 'MH', a3: 'MHL', num: '584' },
  { name: 'Martinique', a2: 'MQ', a3: 'MTQ', num: '474' },
  { name: 'Mauritania', a2: 'MR', a3: 'MRT', num: '478' },
  { name: 'Mauritius', a2: 'MU', a3: 'MUS', num: '480' },
  { name: 'Mayotte', a2: 'YT', a3: 'MYT', num: '175' },
  { name: 'Mexico', a2: 'MX', a3: 'MEX', num: '484' },
  { name: 'Micronesia', prefix: 'Federated States of', a2: 'FM', a3: 'FSM', num: '583' },
  { name: 'Moldova', prefix: 'the Republic of', a2: 'MD', a3: 'MDA', num: '498' },
  { name: 'Monaco', a2: 'MC', a3: 'MCO', num: '492' },
  { name: 'Mongolia', a2: 'MN', a3: 'MNG', num: '496' },
  { name: 'Montenegro', a2: 'ME', a3: 'MNE', num: '499' },
  { name: 'Montserrat', a2: 'MS', a3: 'MSR', num: '500' },
  { name: 'Morocco', a2: 'MA', a3: 'MAR', num: '504' },
  { name: 'Mozambique', a2: 'MZ', a3: 'MOZ', num: '508' },
  { name: 'Myanmar', a2: 'MM', a3: 'MMR', num: '104' },
  { name: 'Namibia', a2: 'NA', a3: 'NAM', num: '516' },
  { name: 'Nauru', a2: 'NR', a3: 'NRU', num: '520' },
  { name: 'Nepal', a2: 'NP', a3: 'NPL', num: '524' },
  { name: 'Netherlands', prefix: 'the', a2: 'NL', a3: 'NLD', num: '528' },
  { name: 'New Caledonia', a2: 'NC', a3: 'NCL', num: '540' },
  { name: 'New Zealand', a2: 'NZ', a3: 'NZL', num: '554' },
  { name: 'Nicaragua', a2: 'NI', a3: 'NIC', num: '558' },
  { name: 'Niger', prefix: 'the', a2: 'NE', a3: 'NER', num: '562' },
  { name: 'Nigeria', a2: 'NG', a3: 'NGA', num: '566' },
  { name: 'Niue', a2: 'NU', a3: 'NIU', num: '570' },
  { name: 'Norfolk Island', a2: 'NF', a3: 'NFK', num: '574' },
  { name: 'Northern Mariana Islands', prefix: 'the', a2: 'MP', a3: 'MNP', num: '580' },
  { name: 'Norway', a2: 'NO', a3: 'NOR', num: '578' },
  { name: 'Oman', a2: 'OM', a3: 'OMN', num: '512' },
  { name: 'Pakistan', a2: 'PK', a3: 'PAK', num: '586' },
  { name: 'Palau', a2: 'PW', a3: 'PLW', num: '585' },
  { name: 'Palestine, State of', a2: 'PS', a3: 'PSE', num: '275' },
  { name: 'Panama', a2: 'PA', a3: 'PAN', num: '591' },
  { name: 'Papua New Guinea', a2: 'PG', a3: 'PNG', num: '598' },
  { name: 'Paraguay', a2: 'PY', a3: 'PRY', num: '600' },
  { name: 'Peru', a2: 'PE', a3: 'PER', num: '604' },
  { name: 'Philippines', prefix: 'the', a2: 'PH', a3: 'PHL', num: '608' },
  { name: 'Pitcairn', a2: 'PN', a3: 'PCN', num: '612' },
  { name: 'Poland', a2: 'PL', a3: 'POL', num: '616' },
  { name: 'Portugal', a2: 'PT', a3: 'PRT', num: '620' },
  { name: 'Puerto Rico', a2: 'PR', a3: 'PRI', num: '630' },
  { name: 'Qatar', a2: 'QA', a3: 'QAT', num: '634' },
  { name: 'Réunion', a2: 'RE', a3: 'REU', num: '638' },
  { name: 'Romania', a2: 'RO', a3: 'ROU', num: '642' },
  { name: 'Russian Federation', prefix: 'the', a2: 'RU', a3: 'RUS', num: '643' },
  { name: 'Rwanda', a2: 'RW', a3: 'RWA', num: '646' },
  { name: 'Saint Barthélemy', a2: 'BL', a3: 'BLM', num: '652' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', a2: 'SH', a3: 'SHN', num: '654' },
  { name: 'Saint Kitts and Nevis', a2: 'KN', a3: 'KNA', num: '659' },
  { name: 'Saint Lucia', a2: 'LC', a3: 'LCA', num: '662' },
  { name: 'Saint Martin', prefix: 'French part', a2: 'MF', a3: 'MAF', num: '663' },
  { name: 'Saint Pierre and Miquelon', a2: 'PM', a3: 'SPM', num: '666' },
  { name: 'Saint Vincent and the Grenadines', a2: 'VC', a3: 'VCT', num: '670' },
  { name: 'Samoa', a2: 'WS', a3: 'WSM', num: '882' },
  { name: 'San Marino', a2: 'SM', a3: 'SMR', num: '674' },
  { name: 'Sao Tome and Principe', a2: 'ST', a3: 'STP', num: '678' },
  { name: 'Saudi Arabia', a2: 'SA', a3: 'SAU', num: '682' },
  { name: 'Senegal', a2: 'SN', a3: 'SEN', num: '686' },
  { name: 'Serbia', a2: 'RS', a3: 'SRB', num: '688' },
  { name: 'Seychelles', a2: 'SC', a3: 'SYC', num: '690' },
  { name: 'Sierra Leone', a2: 'SL', a3: 'SLE', num: '694' },
  { name: 'Singapore', a2: 'SG', a3: 'SGP', num: '702' },
  { name: 'Sint Maarten', prefix: 'Dutch part', a2: 'SX', a3: 'SXM', num: '534' },
  { name: 'Slovakia', a2: 'SK', a3: 'SVK', num: '703' },
  { name: 'Slovenia', a2: 'SI', a3: 'SVN', num: '705' },
  { name: 'Solomon Islands', a2: 'SB', a3: 'SLB', num: '090' },
  { name: 'Somalia', a2: 'SO', a3: 'SOM', num: '706' },
  { name: 'South Africa', a2: 'ZA', a3: 'ZAF', num: '710' },
  { name: 'South Georgia and the South Sandwich Islands', a2: 'GS', a3: 'SGS', num: '239' },
  { name: 'South Sudan', a2: 'SS', a3: 'SSD', num: '728' },
  { name: 'Spain', a2: 'ES', a3: 'ESP', num: '724' },
  { name: 'Sri Lanka', a2: 'LK', a3: 'LKA', num: '144' },
  { name: 'Sudan', prefix: 'the', a2: 'SD', a3: 'SDN', num: '729' },
  { name: 'Suriname', a2: 'SR', a3: 'SUR', num: '740' },
  { name: 'Svalbard and Jan Mayen', a2: 'SJ', a3: 'SJM', num: '744' },
  { name: 'Sweden', a2: 'SE', a3: 'SWE', num: '752' },
  { name: 'Switzerland', a2: 'CH', a3: 'CHE', num: '756' },
  { name: 'Syrian Arab Republic', a2: 'SY', a3: 'SYR', num: '760' },
  { name: 'Taiwan', prefix: 'Province of China', a2: 'TW', a3: 'TWN', num: '158' },
  { name: 'Tajikistan', a2: 'TJ', a3: 'TJK', num: '762' },
  { name: 'Tanzania, United Republic of', a2: 'TZ', a3: 'TZA', num: '834' },
  { name: 'Thailand', a2: 'TH', a3: 'THA', num: '764' },
  { name: 'Timor-Leste', a2: 'TL', a3: 'TLS', num: '626' },
  { name: 'Togo', a2: 'TG', a3: 'TGO', num: '768' },
  { name: 'Tokelau', a2: 'TK', a3: 'TKL', num: '772' },
  { name: 'Tonga', a2: 'TO', a3: 'TON', num: '776' },
  { name: 'Trinidad and Tobago', a2: 'TT', a3: 'TTO', num: '780' },
  { name: 'Tunisia', a2: 'TN', a3: 'TUN', num: '788' },
  { name: 'Turkey', a2: 'TR', a3: 'TUR', num: '792' },
  { name: 'Turkmenistan', a2: 'TM', a3: 'TKM', num: '795' },
  { name: 'Turks and Caicos Islands', prefix: 'the', a2: 'TC', a3: 'TCA', num: '796' },
  { name: 'Tuvalu', a2: 'TV', a3: 'TUV', num: '798' },
  { name: 'Uganda', a2: 'UG', a3: 'UGA', num: '800' },
  { name: 'Ukraine', a2: 'UA', a3: 'UKR', num: '804' },
  { name: 'United Arab Emirates', prefix: 'the', a2: 'AE', a3: 'ARE', num: '784' },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    prefix: 'the',
    a2: 'GB',
    a3: 'GBR',
    num: '826',
  },
  { name: 'United States Minor Outlying Islands', prefix: 'the', a2: 'UM', a3: 'UMI', num: '581' },
  { name: 'United States of America', prefix: 'the', a2: 'US', a3: 'USA', num: '840' },
  { name: 'Uruguay', a2: 'UY', a3: 'URY', num: '858' },
  { name: 'Uzbekistan', a2: 'UZ', a3: 'UZB', num: '860' },
  { name: 'Vanuatu', a2: 'VU', a3: 'VUT', num: '548' },
  { name: 'Venezuela', prefix: 'Bolivarian Republic of', a2: 'VE', a3: 'VEN', num: '862' },
  { name: 'Viet Nam', a2: 'VN', a3: 'VNM', num: '704' },
  { name: 'Virgin Islands', prefix: 'British', a2: 'VG', a3: 'VGB', num: '092' },
  { name: 'Virgin Islands', prefix: 'U.S.', a2: 'VI', a3: 'VIR', num: '850' },
  { name: 'Wallis and Futuna', a2: 'WF', a3: 'WLF', num: '876' },
  { name: 'Western Sahara', a2: 'EH', a3: 'ESH', num: '732' },
  { name: 'Yemen', a2: 'YE', a3: 'YEM', num: '887' },
  { name: 'Zambia', a2: 'ZM', a3: 'ZMB', num: '894' },
  { name: 'Zimbabwe', a2: 'ZW', a3: 'ZWE', num: '716' },
]
